services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:resolute
    entrypoint: /bin/bash
    command: -i -c "sleep infinity"
    volumes:
      - ..:/workspaces/oi-polymarket:cached

    environment:
      - DATABASE_URL=postgresql://oi-polymarket-dev:DEV_PASSWORD@db:5432/oi-polymarket
      - VITE_DEV_HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network

  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_USER=oi-polymarket-dev
      - POSTGRES_PASSWORD=DEV_PASSWORD
      - POSTGRES_DB=oi-polymarket
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oi-polymarket-dev -d oi-polymarket"]
      interval: 1s
      timeout: 1s
      retries: 20
    networks:
      - my-network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
